### ISSUE TITLE
in TopicData site_id and session_id are the same

### ISSUE THREAD

**Issue by ThisisDennis** [rhasspy/rhasspy-hermes-app#145]
I need the caputred audio but also the session id, when i use:

@app.on_topic("rhasspy/asr/{SITE_ID}/{SESSION_ID}/audioCaptured")
async def test_topic1(data: TopicData, payload: bytes):
      #some simple code

in data, session_id and site_id are both just the site_id.
best regards

**Comment by koenvervloesem** [comment]
Can you confirm that the site ID and session ID really differ? For instance, with:

```
mosquitto_sub -t 'rhasspy/asr/+/+/audioCaptured' -F '%t'
```

**Comment by ThisisDennis** [comment]
Thanks for the tip.
No it's the same, so Rhasspy don't send a correct session_id?

**Comment by koenvervloesem** [comment]
Yeah the problem seems to be with Rhasspy, not Rhasspy Hermes App. I looked at the code of Rhasspy Hermes, and there was a bug: the code that creates the MQTT topic for the audioCaptured message used the site ID twice.

I fixed this in https://github.com/rhasspy/rhasspy-hermes/commit/57cc2f5533a9e3a1e93d1adbbaac30541c37f37a. You'll have to wait for a new release, but in the mean time, you can always fix this manually in your Rhasspy setup.

**Comment by ThisisDennis** [comment]
I'm new to docker, so i have no Idea how to fix that code in my setup.
