### ISSUE TITLE
Can't get TTS to work

### ISSUE THREAD

**Issue by Daenara** [rhasspy/rhasspy-hermes-app#77]
Evening,

I found this in the API documentation:
![image](https://user-images.githubusercontent.com/3619315/104487062-ea729800-55cc-11eb-8867-479342d6244c.png)

According to this it should speak what I put into EndSession as text, but my rhasspy keeps silent and I don't see any TTS command over mqtt.

Here is my full code:
```
import logging
from datetime import datetime

from rhasspyhermes.nlu import NluIntent

from rhasspyhermes_app import EndSession, HermesApp

from rhasspy_weather import weather

_LOGGER = logging.getLogger("SkillListener")

app = HermesApp("SkillListener", host="redacted", port=1883, username="redacted", password="redacted")


@app.on_intent("GetTime")
async def get_time(intent: NluIntent):
    """Tell the time."""
    hours = datetime.now().hour
    minutes = datetime.now().minute
    if minutes == 0:
        return EndSession(f"Es ist {hours} Uhr.")
    return EndSession(f"Es ist {hours} Uhr {minutes}.")


@app.on_intent("GetWeatherForecast")
@app.on_intent("GetWeatherForecastTemperature")
@app.on_intent("GetWeatherForecastCondition")
@app.on_intent("GetWeatherForecastItem")
async def get_weather(intent: NluIntent):
    """Get weather"""
    forecast = weather.get_weather_forecast(intent, config_path="../rhasspy_weather_config.ini")
    return EndSession(text=forecast)


app.run()
```

This is what I see on the mqtt server after my intent is finished:

![image](https://user-images.githubusercontent.com/3619315/104487516-7f759100-55cd-11eb-983a-6ac3b6959f11.png)

Did I miss anything in trying to get tts to work, is there an error in the documentation and it should not do tts or did I strumble upon a bug?

**Comment by koenvervloesem** [comment]
It should do TTS. I wonder if it has something to do with the encoding issue https://github.com/rhasspy/rhasspy-hermes-app/issues/78? Do you get a TTS message when there are only ASCII characters in the text?

**Comment by Daenara** [comment]
No, I don't get TTS even when I just put "test" in the end session.

**Comment by koenvervloesem** [comment]
Which version of Rhasspy are you using? When rhasspy-hermes-app sends the EndSession message to the dialogue manager, this should trigger the TTS.

**Comment by Daenara** [comment]
I am using 2.5.8, whatever docker was current last week, I think there was an update without changing the version number in 2.5.8.

**Comment by koenvervloesem** [comment]
OK I have reproduced this here too on 2.5.8, weird. I'll have to investigate this, but that will probably not be before the weekend.

**Comment by koenvervloesem** [comment]
I don't think it has something to do with this library. I had some problems setting up audio on my normal satellite device, so I tried https://github.com/razzo04/rhasspy-mobile-app as a satellite, and when I say "What time is it" to the mobile app, the `examples/time_app.py` app reacts to the recognized intent, sends a `hermes/dialogueManager/endSession` message and then I see a `hermes/tts/say` message appearing.

So it seems to me something in your satellite device not working correctly. Maybe something with the dialogue manager?

**Comment by Daenara** [comment]
I don't even have a satellite, just my one rhasspy docker that does everything. I tried with dialogue management rhasspy and hermes, neither produce any tts output at all. I get the `hermes/dialogueManager/endSession` message, but no tts message appears. If I output via http api or the speech field in the gui, tts works fine.

**Comment by koenvervloesem** [comment]
My first thought was that something changed in the [rhasspyhermes.dialogue.DialogueEndSession](https://rhasspy-hermes.readthedocs.io/en/latest/api.html#rhasspyhermes.dialogue.DialogueEndSession) class and rhasspy-hermes-app hasn't been updated for these changes, but that doesn't seem to be the case. Rhasspy-hermes-app publishes a `DialogueEndSession` object when you return an `EndSession` object, and it just copies over the session ID, text and custom data. Nothing more is needed.

I can reproduce your issue on my non-working satellite, but I can't rule out that this is caused by something else before I get this back in a working state. I can't reproduce your issue with rhasspy-mobile-app. So I'm still struggling to understand where exactly in the Rhasspy stack this is going wrong. Rhasspy-hermes-app is just a wrapper around rhasspy-hermes and it doesn't even need to know about TTS because returning the `EndSession` object just signals to the dialogue manager that it has to end the session. Sending the message to the TTS is the responsibility of the dialogue manager, not of rhasspy-hermes-app.

Do you have some other Rhasspy apps running that do work? Maybe comparing a log of the Hermes messages from a working and a non-working case would give a clue about what's going wrong.

**Comment by Daenara** [comment]
I don't have anything working as of yet, but I still managed to get an example of a working setup and a non working setup, with the same script....

It seems like this is another instance of rhasspy doing something differently when using the web gui instead of starting a session via wakeword... This makes testing anything so much harder.

[not_working.txt](https://github.com/rhasspy/rhasspy-hermes-app/files/5822803/not_working.txt)
[working.txt](https://github.com/rhasspy/rhasspy-hermes-app/files/5822804/working.txt)

Pretty sure the next time I run into anything that should work but doesn't I open an issue for a gui improvement of rhasspy to put it in big red letters that the web gui shouldn't be used to test any functionality of anything that is not the microphone input or the speaker output. I am tired of stuff only working with a working wakeword setup.

Sorry about this slightly aggressive message, I just can't help but stay calm when this problem turns up in another way. I thought for sure it shouldn't affect mqtt in any way because hermes-led does work without problems but aparrently it also affects stuff via mqtt.

**Comment by koenvervloesem** [comment]
Yes it could have something to do with https://github.com/rhasspy/rhasspy/issues/132 which I opened the last time you encountered this issue.
