### ISSUE TITLE
Encoding Issue

### ISSUE THREAD

**Issue by Daenara** [rhasspy/rhasspy-hermes-app#78]
This seems to have a little encoding issue along the way. 

My weather script outputs the sentence
`Nein, morgen gibt es keinen Regen. Das Wetter ist: Bedeckt und mäßiger Wind`

and once it is sent over mqtt by this it ends up as
![image](https://user-images.githubusercontent.com/3619315/104488666-fbbca400-55ce-11eb-921c-7816bbc8cb9a.png)

If I send the sentence over mqtt with my own script, it ends up as it should.

I am pretty sure that this is a missing `ensure_ascii=False` in at least one `json.dumps`.

**Comment by koenvervloesem** [comment]
I think this [has been fixed in rhasspy-hermes 0.5.0](https://github.com/rhasspy/rhasspy-hermes/commit/d8aad674dc36c9dbfeaf8c493768093c06e3061b). I upgraded the dependency requirement now in https://github.com/rhasspy/rhasspy-hermes-app/commit/43556e3da6d9c670ea42ad38f439525c1102d5a4, I will release a new version of rhasspy-hermes-app soon with this update, that should fix your issue.

**Comment by koenvervloesem** [comment]
Can you confirm that this bug is fixed by using [rhasspy-hermes-app 1.1.1](https://github.com/rhasspy/rhasspy-hermes-app/releases/tag/v1.1.1)?

**Comment by Daenara** [comment]
It is fixed now, thanks
